#!/bin/zsh

git submodule init
git submodule update
git submodule foreach 'git pull origin master'

for f in .*; do
  if test ! .git = $f && test ! .gitmodules = $f; then
    rm -f ~/$f
    ln -sfv `pwd`/$f ~/$f
  fi
done
